### ISSUE TITLE
Evaluation results overlay minimap

### ISSUE THREAD

**Issue by staticfloat** [JunoLab/atom-ink#103]
Large evaluation results overlay a minimap on the right.

<img width="898" alt="screen shot 2016-12-15 at 11 57 51 am" src="https://cloud.githubusercontent.com/assets/130920/21239902/c0ce5954-c2bd-11e6-8576-19713545b588.png">

**Comment by pfitzseb** [comment]
You can fix that by including
```less
atom-text-editor::shadow  atom-text-editor-minimap { // `::shadow` will be unnecessary for Atom >= 1.13
  z-index: 5;
}
```
in your `styles.less` stylesheet. atom-minimap doesn't define any `z-index` for itself though, and our overlays have to -- so unless we were to add the above defintion (which feels wrong to me), there's no way for ink to really solve this.
